name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish:
    strategy:
      fail-fast: false
      matrix:
        include:
          # https://doc.rust-lang.org/rustc/platform-support.html
          - os: ubuntu-latest
            target: x86_64-unknown-linux-gnu
            artifact_name: novel-cli
          - os: windows-latest
            target: x86_64-pc-windows-msvc
            artifact_name: novel-cli.exe
          - os: macos-latest
            target: x86_64-apple-darwin
            artifact_name: novel-cli
          - os: macos-latest
            target: aarch64-apple-darwin
            artifact_name: novel-cli

    name: Publish for ${{ matrix.os }}-${{ matrix.target }}
    runs-on: ${{ matrix.os }}

    steps:
      # https://github.com/actions/checkout
      - name: Checkout
        uses: actions/checkout@v3

      # https://github.com/Swatinem/rust-cache
      - name: Cache
        uses: Swatinem/rust-cache@v2

      # https://github.com/dtolnay/rust-toolchain
      - name: Install toolchain
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: stable
          targets: ${{ matrix.target }}

      # https://github.com/taiki-e/install-action
      - name: Install cargo-semver-checks
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: taiki-e/install-action@v2
        with:
          tool: cargo-semver-checks

      # https://github.com/obi1kenobi/cargo-semver-checks-action
      - name: Check semver
        if: ${{ matrix.os == 'ubuntu-latest' }}
        uses: obi1kenobi/cargo-semver-checks-action@v1
        with:
          version-tag-prefix: ""

      - name: Publish
        if: ${{ matrix.os == 'ubuntu-latest' }}
        run: cargo publish --token ${{ secrets.CARGO_REGISTRY_TOKEN }}

      # https://github.com/ilammy/setup-nasm
      - name: Install NASM
        if: ${{ matrix.os == 'windows-latest' }}
        uses: ilammy/setup-nasm@v1

      - name: Build
        run: cargo build --release --target ${{ matrix.target }}

      # https://github.com/svenstaro/upx-action
      - name: Compress binaries
        # TODO Use it on macOS
        # See https://github.com/upx/upx/issues/612
        if: ${{ !endsWith(matrix.target, 'apple-darwin') }}
        uses: svenstaro/upx-action@v2
        with:
          files: |
            target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      - name: Permission
        if: ${{ matrix.os != 'windows-latest' }}
        run: chmod +x target/${{ matrix.target }}/release/${{ matrix.artifact_name }}

      # https://github.com/TheDoctor0/zip-release
      - name: Archive Release
        uses: thedoctor0/zip-release@0.7.1
        with:
          type: zip
          filename: release.zip
          path: ${{ matrix.artifact_name }}
          directory: target/${{ matrix.target }}/release

      # https://github.com/svenstaro/upload-release-action
      - name: Upload binary to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: target/${{ matrix.target }}/release/release.zip
          asset_name: novel-cli-${{ matrix.target }}.zip
          overwrite: true
